## Tarea 5 
Realizar una matriz con numeros aleatorio y extraer su diagonal 

In [1]:
import numpy as np

In [2]:
from numpy import random

In [3]:
M=random.rand(16).reshape((4,4))
print M

[[ 0.52712493  0.54162738  0.17062923  0.41017924]
 [ 0.2947693   0.19097956  0.15411118  0.26480655]
 [ 0.23225964  0.76782059  0.66735435  0.2802758 ]
 [ 0.93161476  0.59277072  0.98630169  0.53278284]]


In [4]:
np.diag(M)

array([ 0.52712493,  0.19097956,  0.66735435,  0.53278284])